services:
  - type: web
    name: jambo-translator
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python translator_backend.py"
    envVars:
      - key: OPENAI_API_KEY
        sync: false
